#!/bin/bash

# any failure should exit the script early
set -e

# when the script exits, run this code to cleanup
trap "docker-compose down" EXIT

# run the tests
#docker-compose down
#docker-compose up -d --build --force-recreate --remove-orphans selenium-hub selenium-firefox-node selenium-chrome-node bagcupid
#docker-compose build bagcupid-tests
#docker-compose run bagcupid-tests
